[colors.bright]
black = "#75715E"
blue = "#66D9EF"
cyan = "#A1EFE4"
green = "#A6E22E"
magenta = "#AE81FF"
red = "#F92672"
white = "#F9F8F5"
yellow = "#F4BF75"

[colors.normal]
black = "#272822"
blue = "#66D9EF"
cyan = "#A1EFE4"
green = "#A6E22E"
magenta = "#AE81FF"
red = "#F92672"
white = "#F8F8F2"
yellow = "#F4BF75"

[colors.primary]
background = "#2D2A2E"
foreground = "#E3E1E4"

[font]
size = 11

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"

[mouse]
hide_when_typing = true

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.75
startup_mode = "Windowed"

[window.dimensions]
columns = 90
lines = 32

[window.padding]
x = 12
y = 12
